FROM quay.io/fedora/fedora:latest
RUN dnf install -y ethtool lsof iproute nmap-ncat NetworkManager iputils yq util-linux gawk && \
    mkdir -p /app && dnf clean all
COPY gather-facts.sh /app/
RUN chmod 775 /app/gather-facts.sh
CMD ["/app/gather-facts.sh"]
